#!/usr/bin/env python3
"""
Docker Monitor v2.0 - Modular Real-time Docker Dashboard
Author: David Smidke - Accenture
Generated by GitHub Copilot

Real-time container monitoring with:
  • Advanced command extraction from running containers
  • Docker health checking and image analysis
  • Network statistics and system monitoring
  • Update checking for app and Docker images
  • Multi-panel dashboard with keyboard navigation
  • Thread-safe async worker pattern
  • Persistent settings and theme support

Compatible with Python 3.7+ on Linux x86_64/ARM64.
Tested on: Raspberry Pi 5, NUC (Proxmox LXC), Ubuntu 22.04+

Security: Input validation, subprocess timeouts, no privilege escalation
Accessibility: WCAG 2.1 AA compliant, full keyboard navigation
Sustainability: Efficient polling, minimal CPU usage, async I/O
"""

import sys
import logging

# ============================================================================
# PYTHON VERSION CHECK
# ============================================================================

PYTHON_VERSION = sys.version_info
if PYTHON_VERSION < (3, 7):
    print(f"ERROR: Python 3.7+ required. Found: {PYTHON_VERSION.major}.{PYTHON_VERSION.minor}")
    sys.exit(1)

# ============================================================================
# IMPORTS FROM MODULAR ARCHITECTURE
# ============================================================================

from docker_config import Config, EDITABLE_SETTINGS, APP_VERSION
from docker_models import (
    CacheData, ContainerInfo, ImageInfo, LogEntry, 
    SystemStats, DockerRunCommand, UpdateInfo
)
from docker_themes import THEME_DEFINITIONS, THEME_NAMES, init_curses_colors
from docker_utils import (
    DockerCommandExtractor, DockerImageAnalyzer, 
    DockerHealthChecker, DockerNetworkInspector
)
from docker_network import CommandExecutor, SystemInfo, NetworkStatsCollector, UpdateChecker
from docker_worker import DataCollectionWorker, perform_docker_action
from docker_main import DockerMonitor, main

# ============================================================================
# BACKWARD COMPATIBILITY / MODULE EXPORTS
# ============================================================================

"""
All classes and functions are now available from their respective modules:
  • docker_config: Config, EDITABLE_SETTINGS, APP_VERSION
  • docker_models: CacheData, ContainerInfo, LogEntry, SystemStats, etc.
  • docker_themes: THEME_DEFINITIONS, THEME_NAMES
  • docker_utils: DockerCommandExtractor, DockerImageAnalyzer, etc.
  • docker_network: CommandExecutor, SystemInfo, NetworkStatsCollector
  • docker_worker: DataCollectionWorker
  • docker_main: DockerMonitor

For backward compatibility, all exports are available at module level.
"""

__version__ = APP_VERSION
__author__ = "David Smidke - Accenture"
__all__ = [
    'Config', 'EDITABLE_SETTINGS', 'APP_VERSION',
    'ContainerInfo', 'ImageInfo', 'LogEntry', 'SystemStats', 'CacheData',
    'THEME_DEFINITIONS', 'THEME_NAMES',
    'DockerCommandExtractor', 'DockerImageAnalyzer', 'DockerHealthChecker',
    'CommandExecutor', 'SystemInfo', 'NetworkStatsCollector', 'UpdateChecker',
    'DataCollectionWorker', 'DockerMonitor', 'main'
]


# ============================================================================
# ENTRY POINT
# ============================================================================

if __name__ == "__main__":
    main()
