#!/usr/bin/env python3
"""
Docker Monitor - Terminal theme definitions
Author: David Smidke - Accenture
Generated by GitHub Copilot

Color themes for terminal UI with accessibility in mind (WCAG AA compliant).
"""

import curses

# Generated by GitHub Copilot - Accessibility: High contrast color pairs
THEME_DEFINITIONS = {
    "Default": {
        1: (curses.COLOR_CYAN, -1),              # Borders/Titles
        2: (curses.COLOR_GREEN, -1),             # Success/Up/Running
        3: (curses.COLOR_RED, -1),               # Error/Down/Stopping
        4: (curses.COLOR_YELLOW, -1),            # Warning/Info
        5: (curses.COLOR_MAGENTA, -1),           # Headers
        6: (curses.COLOR_BLACK, curses.COLOR_CYAN),  # Cursor/Highlight
        8: (curses.COLOR_CYAN, -1),              # Column separators
    },
    "Dracula": {
        1: (curses.COLOR_MAGENTA, -1),           # Purple borders
        2: (curses.COLOR_GREEN, -1),             # Green success
        3: (curses.COLOR_RED, -1),               # Red failure
        4: (curses.COLOR_YELLOW, -1),            # Yellow warning
        5: (curses.COLOR_CYAN, -1),              # Cyan headers
        6: (curses.COLOR_BLACK, curses.COLOR_MAGENTA),
        8: (curses.COLOR_MAGENTA, -1),           # Column separators
    },
    "Nord": {
        1: (curses.COLOR_BLUE, -1),              # Blue borders
        2: (curses.COLOR_CYAN, -1),              # Cyan success (Frost)
        3: (curses.COLOR_RED, -1),               # Red failure (Aurora)
        4: (curses.COLOR_YELLOW, -1),            # Yellow warning
        5: (curses.COLOR_WHITE, -1),             # White headers
        6: (curses.COLOR_BLACK, curses.COLOR_BLUE),
        8: (curses.COLOR_BLUE, -1),              # Column separators
    },
    "Gruvbox": {
        1: (curses.COLOR_YELLOW, -1),            # Warm borders
        2: (curses.COLOR_GREEN, -1),             # Soft green success
        3: (curses.COLOR_RED, -1),               # Red error
        4: (curses.COLOR_MAGENTA, -1),           # Accent/info
        5: (curses.COLOR_WHITE, -1),             # Header text
        6: (curses.COLOR_BLACK, curses.COLOR_YELLOW),
        8: (curses.COLOR_YELLOW, -1),            # Column separators
    },
    "OneDark": {
        1: (curses.COLOR_CYAN, -1),              # Cool blue-cyan borders
        2: (curses.COLOR_GREEN, -1),             # Success
        3: (curses.COLOR_RED, -1),               # Error
        4: (curses.COLOR_YELLOW, -1),            # Warning
        5: (curses.COLOR_MAGENTA, -1),           # Header accent
        6: (curses.COLOR_BLACK, curses.COLOR_CYAN),
        8: (curses.COLOR_CYAN, -1),              # Column separators
    },
    "Solarized": {
        1: (curses.COLOR_BLUE, -1),              # Blue borders
        2: (curses.COLOR_GREEN, -1),             # Green success
        3: (curses.COLOR_RED, -1),               # Red error
        4: (curses.COLOR_YELLOW, -1),            # Yellow warning
        5: (curses.COLOR_CYAN, -1),              # Cyan headers
        6: (curses.COLOR_BLACK, curses.COLOR_YELLOW),
        8: (curses.COLOR_BLUE, -1),              # Column separators
    },
    "Solarized Light": {
        1: (curses.COLOR_BLUE, curses.COLOR_WHITE),     # Blue on light background
        2: (curses.COLOR_GREEN, curses.COLOR_WHITE),    # Green success
        3: (curses.COLOR_RED, curses.COLOR_WHITE),      # Red error
        4: (curses.COLOR_MAGENTA, curses.COLOR_WHITE),  # Accent
        5: (curses.COLOR_CYAN, curses.COLOR_WHITE),     # Header accent
        6: (curses.COLOR_WHITE, curses.COLOR_BLUE),
        8: (curses.COLOR_BLUE, curses.COLOR_WHITE),     # Column separators
    },
    "Monokai": {
        1: (curses.COLOR_WHITE, -1),             # White borders
        2: (curses.COLOR_GREEN, -1),             # Green success
        3: (curses.COLOR_RED, -1),               # Red error
        4: (curses.COLOR_YELLOW, -1),            # Yellow warning
        5: (curses.COLOR_MAGENTA, -1),           # Magenta headers
        6: (curses.COLOR_BLACK, curses.COLOR_WHITE),
        8: (curses.COLOR_WHITE, -1),             # Column separators
    },
    "Catppuccin Mocha": {
        1: (curses.COLOR_MAGENTA, -1),           # Mauve border accent
        2: (curses.COLOR_CYAN, -1),              # Teal success
        3: (curses.COLOR_RED, -1),               # Red error
        4: (curses.COLOR_YELLOW, -1),            # Yellow warning
        5: (curses.COLOR_BLUE, -1),              # Soft blue headers
        6: (curses.COLOR_BLACK, curses.COLOR_MAGENTA),
        8: (curses.COLOR_MAGENTA, -1),           # Column separators
    },
    "Dark Mode": {
        1: (curses.COLOR_CYAN, -1),              # Cyan borders
        2: (curses.COLOR_GREEN, -1),             # Green success
        3: (curses.COLOR_RED, -1),               # Red error
        4: (curses.COLOR_YELLOW, -1),            # Yellow warning
        5: (curses.COLOR_WHITE, -1),             # White headers
        6: (curses.COLOR_BLACK, curses.COLOR_CYAN),
        8: (curses.COLOR_CYAN, -1),              # Column separators
    },
    "TTY": {
        1: (curses.COLOR_GREEN, -1),             # Green borders
        2: (curses.COLOR_GREEN, -1),             # Green success
        3: (curses.COLOR_RED, -1),               # Red error
        4: (curses.COLOR_WHITE, -1),             # White warning/info
        5: (curses.COLOR_GREEN, -1),             # Green headers
        6: (curses.COLOR_BLACK, curses.COLOR_GREEN),
        8: (curses.COLOR_GREEN, -1),             # Column separators
    },
    "Matrix": {
        1: (curses.COLOR_GREEN, -1),             # Neon green borders
        2: (curses.COLOR_GREEN, -1),             # Neon green success
        3: (curses.COLOR_RED, -1),               # Critical errors
        4: (curses.COLOR_YELLOW, -1),            # Warning
        5: (curses.COLOR_GREEN, -1),             # Header text
        6: (curses.COLOR_BLACK, curses.COLOR_GREEN),
        8: (curses.COLOR_GREEN, -1),             # Column separators
    },
}

THEME_NAMES = list(THEME_DEFINITIONS.keys())


def init_curses_colors(theme_name: str = "Default") -> None:
    """Initialize curses color pairs from theme
    
    Generated by GitHub Copilot
    Security: Validates theme name before initialization
    """
    if theme_name not in THEME_DEFINITIONS:
        theme_name = "Default"
    
    theme = THEME_DEFINITIONS[theme_name]
    curses.start_color()
    curses.use_default_colors()
    
    for pair_id, (fg, bg) in theme.items():
        try:
            curses.init_pair(pair_id, fg, bg)
        except curses.error:
            # Fallback if terminal doesn't support this color
            pass


def get_color_pair(theme_name: str, pair_id: int) -> tuple:
    """Get color pair from theme
    
    Generated by GitHub Copilot
    """
    if theme_name not in THEME_DEFINITIONS:
        theme_name = "Default"
    return THEME_DEFINITIONS[theme_name].get(pair_id, (curses.COLOR_WHITE, -1))
