#!/usr/bin/env python3
"""
Docker Monitor - Data models and structures
Author: David Smidke - Accenture
Generated by GitHub Copilot

Data structures for containers, images, logs, and statistics.
"""

import time
from dataclasses import dataclass, field
from typing import Dict, List, Set, Optional, Any
from datetime import datetime


@dataclass
class ContainerInfo:
    """Container metadata and statistics"""
    id: str
    name: str
    image: str
    status: str
    cpu_perc: str = "0.00%"
    mem_usage: str = "0B"
    mem_perc: str = "0.00%"
    net_io: str = "0B / 0B"
    pids: str = "0"
    created: str = ""
    ports: str = ""
    network_name: str = ""
    ip_address: str = ""
    command: str = ""
    health_status: Optional['HealthStatus'] = None
    
    @property
    def is_running(self) -> bool:
        return "Up" in self.status
    
    @property
    def display_name(self) -> str:
        return self.name if len(self.name) < 30 else self.name[:27] + "..."


@dataclass
class ImageInfo:
    """Docker image metadata"""
    id: str
    repo_tag: str
    size: str
    created: str
    containers: int = 0
    
    @property
    def short_id(self) -> str:
        return self.id[:12]


@dataclass
class LogEntry:
    """Log entry with metadata"""
    container_name: str
    message: str
    level: str = "INFO"
    capture_time: float = field(default_factory=time.time)
    
    @property
    def hash_id(self) -> int:
        """Unique hash for deduplication"""
        return hash((self.container_name, self.message[:300]))
    
    @property
    def formatted_time(self) -> str:
        return datetime.fromtimestamp(self.capture_time).strftime('%H:%M:%S')


@dataclass
class HostNetwork:
    """Host network interface statistics"""
    interface: str = "eth0"
    rx_bytes_sec: float = 0.0
    tx_bytes_sec: float = 0.0
    rx_packets_sec: float = 0.0
    tx_packets_sec: float = 0.0


@dataclass
class DockerRunCommand:
    """Extracted docker run command with analysis"""
    container_id: str
    command: str
    ports: List[str] = field(default_factory=list)
    volumes: List[str] = field(default_factory=list)
    environment_vars: Dict[str, str] = field(default_factory=dict)
    image: str = ""
    networks: List[str] = field(default_factory=list)


@dataclass
class SystemStats:
    """System-level statistics"""
    containers_running: int = 0
    containers_total: int = 0
    images_total: int = 0
    memory_used: str = "0B"
    cpu_available: int = 0
    uptime_seconds: int = 0


@dataclass
class HealthStatus:
    """Container health check status - Generated by GitHub Copilot"""
    status: str  # "healthy", "unhealthy", "starting", "none"
    checked_count: int = 0
    failed_count: int = 0
    last_check: float = field(default_factory=time.time)
    
    @property
    def is_healthy(self) -> bool:
        return self.status == "healthy"
    
    @property
    def is_unhealthy(self) -> bool:
        return self.status == "unhealthy"
    
    @property
    def is_starting(self) -> bool:
        return self.status == "starting"
    
    @property
    def fail_rate(self) -> float:
        """Failure rate as percentage"""
        if self.checked_count == 0:
            return 0.0
        return (self.failed_count / self.checked_count) * 100


@dataclass
class UpdateInfo:
    """Application/image update information"""
    available: bool = False
    version: str = ""
    download_url: str = ""
    release_notes: str = ""
    image_updates: List[str] = field(default_factory=list)  # Container IDs with updates
    check_time: float = field(default_factory=time.time)


@dataclass
class ContainerMetadata:
    """Enhanced container metadata for Portainer-like features - Generated by GitHub Copilot"""
    container_id: str
    tags: List[str] = field(default_factory=list)  # User-defined tags
    labels: Dict[str, str] = field(default_factory=dict)  # Docker labels
    stack_name: str = ""  # Associated compose stack
    service_name: str = ""  # Service name within stack
    group: str = "default"  # Container grouping
    notes: str = ""  # User notes
    last_restart: float = 0.0
    restarts: int = 0


@dataclass
class ResourceMetrics:
    """Performance metrics for trending - Green Software monitoring"""
    timestamp: float = field(default_factory=time.time)
    cpu_percent: float = 0.0
    memory_mb: float = 0.0
    network_rx_mb: float = 0.0
    network_tx_mb: float = 0.0


class CacheData:
    """Thread-safe cache for application state - Generated by GitHub Copilot"""
    __slots__ = (
        'running', 'paused', 'containers', 'logs', 'images', 'net',
        'log_hashes', 'start_time', 'ready', 'selected_idx', 'settings_mode',
        'theme_mode', 'settings_cursor', 'theme_cursor', 'worker_paused',
        'applied_filter', 'input_mode', 'typing_buffer', 'focus_enabled',
        'focused_section', 'scroll_offsets', 'section_heights', 'section_content_heights',
        'section_priority', 'active_logs_container', 'show_sections', 'last_update_check',
        'update_available', 'modal_state', 'modal_target_id', 'modal_target_name',
        'modal_msg', 'menu_cursor', 'confirm_action', 'confirm_cursor', 'msg_timer', 'docker_run_commands', 'system_stats',
        # Portainer-like features
        'stacks', 'volumes', 'networks', 'container_metadata', 'resource_history',
        'current_view', 'search_query', 'filter_tags', 'view_mode',
        # Lazydocker-inspired features - Generated by GitHub Copilot
        'task_manager', 'metrics_collector', 'event_monitor'
    )

    def __init__(self):
        # Generated by GitHub Copilot - Multi-field initialization for thread-safe operations
        self.running = True
        self.paused = False
        self.containers: List[ContainerInfo] = []
        self.logs: List[LogEntry] = []
        self.images: List[ImageInfo] = []
        self.net = HostNetwork()
        self.log_hashes: Set[int] = set()
        self.start_time = time.time()
        self.ready = False
        
        # UI state
        self.selected_idx = 0
        self.settings_mode = False
        self.theme_mode = False
        self.settings_cursor = 0
        self.theme_cursor = 0
        self.worker_paused = False
        self.applied_filter = ""
        self.input_mode = False
        self.typing_buffer = ""
        self.focus_enabled = True  # Focus system enabled by default
        self.focused_section = "containers"  # Currently focused section for scrolling
        self.scroll_offsets: Dict[str, int] = {s: 0 for s in ['containers', 'logs', 'images', 'stats']}
        self.section_heights: Dict[str, int] = {}  # Allocated height for each section (set by UI)
        self.section_content_heights: Dict[str, int] = {}  # Content height for each section (set by UI)
        self.show_sections: Dict[str, bool] = {
            'containers': True,
            'logs': True,
            'images': False,
            'stats': False,
        }
        # Section display order and priority
        self.section_priority = ['containers', 'logs', 'images', 'stats']  # Order displayed top-to-bottom
        self.active_logs_container = ""
        
        # Update checking
        self.last_update_check = 0.0
        self.update_available: Optional[UpdateInfo] = None
        
        # Modal interaction
        self.modal_state: Optional[str] = None
        self.modal_target_id = ""
        self.modal_target_name = ""
        self.modal_msg = ""
        self.menu_cursor = 0
        self.confirm_action = ""
        self.confirm_cursor = 0
        self.msg_timer = 0.0
        
        # Advanced data
        self.docker_run_commands: Dict[str, DockerRunCommand] = {}
        self.system_stats = SystemStats()
        
        # Portainer-like features - Generated by GitHub Copilot
        self.stacks: Dict[str, Any] = {}  # Compose stacks
        self.volumes: Dict[str, Any] = {}  # Docker volumes
        self.networks: Dict[str, Any] = {}  # Docker networks
        self.container_metadata: Dict[str, ContainerMetadata] = {}  # Enhanced metadata
        self.resource_history: Dict[str, List[ResourceMetrics]] = {}  # Performance trending
        
        # Views and search
        self.current_view = "containers"  # 'containers', 'stacks', 'volumes', 'networks'
        self.search_query = ""
        self.filter_tags: List[str] = []
        self.view_mode = "list"  # 'list', 'grid', 'compact'
        
        # Lazydocker-inspired features - Generated by GitHub Copilot
        self.task_manager: Any = None  # Will be set by main app
        self.metrics_collector: Any = None  # Will be set by main app
        self.event_monitor: Any = None  # Will be set by main app
